/**
 * User-friendly error messages for the application.
 * All messages are:
 * - Non-technical (no HTTP codes, stack traces, etc.)
 * - Actionable (tell user what to do)
 * - Empathetic in tone
 * - Following brand voice: warm, smart, reliable
 *
 * Generated by copywriter agent - do not modify without consulting brand guidelines.
 */

export const ERROR_MESSAGES = {
  // Network/connection errors
  CONNECTION_LOST:
    "We got disconnected for a moment. I'm reconnecting now so we can pick up where we left off.",
  CONNECTION_FAILED:
    "I'm having trouble connecting right now. Check your internet connection, then refresh the page to try again.",

  // AI/Chat errors
  AI_REQUEST_FAILED: 'Something went wrong with that request. Let me try again for you.',
  AI_TIMEOUT: 'This is taking longer than usual. Let me start fresh with that request.',
  MESSAGE_SEND_FAILED: "Your message didn't go through. Try sending it again.",

  // Booking errors
  BOOKING_FAILED:
    "Something went wrong and your booking didn't go through. Let's try that again, or I can show you other available times.",
  PROVIDER_LOAD_FAILED:
    "I'm having trouble loading the details for that provider. Try selecting them again, or I can show you other options.",
  AVAILABILITY_LOAD_FAILED:
    "I couldn't load the available times for this provider. Let me try again, or we can check another provider's availability.",

  // Calendar errors
  CALENDAR_UNAVAILABLE:
    "Calendar sync isn't available right now, but your booking is still confirmed. You'll get a confirmation email with all the details.",
  CALENDAR_ADD_FAILED:
    "Couldn't add this to your calendar, but your booking is confirmed. You'll find all the details in your confirmation email.",

  // Generic errors
  SOMETHING_WENT_WRONG: 'Something unexpected happened. Let me try that again for you.',
  TRY_AGAIN_LATER:
    "I'm having technical difficulties right now. Please check back in a few minutes - I should be working normally again soon.",
} as const;

export type ErrorMessageKey = keyof typeof ERROR_MESSAGES;

/**
 * Get a user-friendly error message.
 * Always returns a user-friendly message, never exposes technical details.
 */
export function getUserFriendlyError(
  _error: unknown,
  fallback: ErrorMessageKey = 'SOMETHING_WENT_WRONG'
): string {
  // Always return user-friendly message, never expose technical details
  return ERROR_MESSAGES[fallback];
}
